//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PackageTracking.Droid.ru.russianpost.tracking {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OperationHistory12PortBinding", Namespace="http://russianpost.org/operationhistory")]
    public partial class OperationHistory12 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOperationHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLanguagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomDutyEventsForMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSmsHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalOrderEventsForMailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OperationHistory12() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://tracking.russianpost.ru/rtm34";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOperationHistoryCompletedEventHandler getOperationHistoryCompleted;
        
        /// <remarks/>
        public event getLanguagesCompletedEventHandler getLanguagesCompleted;
        
        /// <remarks/>
        public event getCustomDutyEventsForMailCompletedEventHandler getCustomDutyEventsForMailCompleted;
        
        /// <remarks/>
        public event getSmsHistoryCompletedEventHandler getSmsHistoryCompleted;
        
        /// <remarks/>
        public event PostalOrderEventsForMailCompletedEventHandler PostalOrderEventsForMailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://russianpost.org/operationhistory", ResponseNamespace="http://russianpost.org/operationhistory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("OperationHistoryData", Namespace="http://russianpost.org/operationhistory/data")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("historyRecord")]
        public OperationHistoryRecord[] getOperationHistory([System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] OperationHistoryRequest OperationHistoryRequest, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] AuthorizationHeader AuthorizationHeader) {
            object[] results = this.Invoke("getOperationHistory", new object[] {
                        OperationHistoryRequest,
                        AuthorizationHeader});
            return ((OperationHistoryRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void getOperationHistoryAsync(OperationHistoryRequest OperationHistoryRequest, AuthorizationHeader AuthorizationHeader) {
            this.getOperationHistoryAsync(OperationHistoryRequest, AuthorizationHeader, null);
        }
        
        /// <remarks/>
        public void getOperationHistoryAsync(OperationHistoryRequest OperationHistoryRequest, AuthorizationHeader AuthorizationHeader, object userState) {
            if ((this.getOperationHistoryOperationCompleted == null)) {
                this.getOperationHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationHistoryOperationCompleted);
            }
            this.InvokeAsync("getOperationHistory", new object[] {
                        OperationHistoryRequest,
                        AuthorizationHeader}, this.getOperationHistoryOperationCompleted, userState);
        }
        
        private void OngetOperationHistoryOperationCompleted(object arg) {
            if ((this.getOperationHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOperationHistoryCompleted(this, new getOperationHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://russianpost.org/operationhistory", ResponseNamespace="http://russianpost.org/operationhistory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("LanguageData", Namespace="http://russianpost.org/operationhistory/data")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Language", IsNullable=false)]
        public LanguageDataLanguage[] getLanguages([System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] AuthorizationHeader AuthorizationHeader) {
            object[] results = this.Invoke("getLanguages", new object[] {
                        AuthorizationHeader});
            return ((LanguageDataLanguage[])(results[0]));
        }
        
        /// <remarks/>
        public void getLanguagesAsync(AuthorizationHeader AuthorizationHeader) {
            this.getLanguagesAsync(AuthorizationHeader, null);
        }
        
        /// <remarks/>
        public void getLanguagesAsync(AuthorizationHeader AuthorizationHeader, object userState) {
            if ((this.getLanguagesOperationCompleted == null)) {
                this.getLanguagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLanguagesOperationCompleted);
            }
            this.InvokeAsync("getLanguages", new object[] {
                        AuthorizationHeader}, this.getLanguagesOperationCompleted, userState);
        }
        
        private void OngetLanguagesOperationCompleted(object arg) {
            if ((this.getLanguagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLanguagesCompleted(this, new getLanguagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://russianpost.org/operationhistory", ResponseNamespace="http://russianpost.org/operationhistory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CustomDutyEventsForMailOutput", Namespace="http://www.russianpost.org/custom-duty-info/data")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomDutyEvent[] getCustomDutyEventsForMail([System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] AuthorizationHeader AuthorizationHeader, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")] CustomDutyEventsForMailInput CustomDutyEventsForMailInput) {
            object[] results = this.Invoke("getCustomDutyEventsForMail", new object[] {
                        AuthorizationHeader,
                        CustomDutyEventsForMailInput});
            return ((CustomDutyEvent[])(results[0]));
        }
        
        /// <remarks/>
        public void getCustomDutyEventsForMailAsync(AuthorizationHeader AuthorizationHeader, CustomDutyEventsForMailInput CustomDutyEventsForMailInput) {
            this.getCustomDutyEventsForMailAsync(AuthorizationHeader, CustomDutyEventsForMailInput, null);
        }
        
        /// <remarks/>
        public void getCustomDutyEventsForMailAsync(AuthorizationHeader AuthorizationHeader, CustomDutyEventsForMailInput CustomDutyEventsForMailInput, object userState) {
            if ((this.getCustomDutyEventsForMailOperationCompleted == null)) {
                this.getCustomDutyEventsForMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomDutyEventsForMailOperationCompleted);
            }
            this.InvokeAsync("getCustomDutyEventsForMail", new object[] {
                        AuthorizationHeader,
                        CustomDutyEventsForMailInput}, this.getCustomDutyEventsForMailOperationCompleted, userState);
        }
        
        private void OngetCustomDutyEventsForMailOperationCompleted(object arg) {
            if ((this.getCustomDutyEventsForMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomDutyEventsForMailCompleted(this, new getCustomDutyEventsForMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://russianpost.org/operationhistory", ResponseNamespace="http://russianpost.org/operationhistory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("SmsHistoryData", Namespace="http://russianpost.org/sms-info/data")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("historyRecord")]
        public SmsHistoryRecord[] getSmsHistory([System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] AuthorizationHeader AuthorizationHeader, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/sms-info/data")] SmsHistoryRequest SmsHistoryRequest) {
            object[] results = this.Invoke("getSmsHistory", new object[] {
                        AuthorizationHeader,
                        SmsHistoryRequest});
            return ((SmsHistoryRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void getSmsHistoryAsync(AuthorizationHeader AuthorizationHeader, SmsHistoryRequest SmsHistoryRequest) {
            this.getSmsHistoryAsync(AuthorizationHeader, SmsHistoryRequest, null);
        }
        
        /// <remarks/>
        public void getSmsHistoryAsync(AuthorizationHeader AuthorizationHeader, SmsHistoryRequest SmsHistoryRequest, object userState) {
            if ((this.getSmsHistoryOperationCompleted == null)) {
                this.getSmsHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSmsHistoryOperationCompleted);
            }
            this.InvokeAsync("getSmsHistory", new object[] {
                        AuthorizationHeader,
                        SmsHistoryRequest}, this.getSmsHistoryOperationCompleted, userState);
        }
        
        private void OngetSmsHistoryOperationCompleted(object arg) {
            if ((this.getSmsHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSmsHistoryCompleted(this, new getSmsHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://russianpost.org/operationhistory", ResponseNamespace="http://russianpost.org/operationhistory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("PostalOrderEventsForMaiOutput", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PostalOrderEvent[] PostalOrderEventsForMail([System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")] AuthorizationHeader AuthorizationHeader, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")] PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            object[] results = this.Invoke("PostalOrderEventsForMail", new object[] {
                        AuthorizationHeader,
                        PostalOrderEventsForMailInput});
            return ((PostalOrderEvent[])(results[0]));
        }
        
        /// <remarks/>
        public void PostalOrderEventsForMailAsync(AuthorizationHeader AuthorizationHeader, PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            this.PostalOrderEventsForMailAsync(AuthorizationHeader, PostalOrderEventsForMailInput, null);
        }
        
        /// <remarks/>
        public void PostalOrderEventsForMailAsync(AuthorizationHeader AuthorizationHeader, PostalOrderEventsForMailInput PostalOrderEventsForMailInput, object userState) {
            if ((this.PostalOrderEventsForMailOperationCompleted == null)) {
                this.PostalOrderEventsForMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalOrderEventsForMailOperationCompleted);
            }
            this.InvokeAsync("PostalOrderEventsForMail", new object[] {
                        AuthorizationHeader,
                        PostalOrderEventsForMailInput}, this.PostalOrderEventsForMailOperationCompleted, userState);
        }
        
        private void OnPostalOrderEventsForMailOperationCompleted(object arg) {
            if ((this.PostalOrderEventsForMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalOrderEventsForMailCompleted(this, new PostalOrderEventsForMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRequest {
        
        private string barcodeField;
        
        private int messageTypeField;
        
        private string languageField;
        
        public OperationHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public int MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEvent {
        
        private string numberField;
        
        private System.DateTime eventDateTimeField;
        
        private bool eventDateTimeFieldSpecified;
        
        private string eventTypeField;
        
        private string eventNameField;
        
        private string indexToField;
        
        private string indexEventField;
        
        private string sumPaymentForwardField;
        
        private string countryEventCodeField;
        
        private string countryToCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateTimeSpecified {
            get {
                return this.eventDateTimeFieldSpecified;
            }
            set {
                this.eventDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexTo {
            get {
                return this.indexToField;
            }
            set {
                this.indexToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexEvent {
            get {
                return this.indexEventField;
            }
            set {
                this.indexEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SumPaymentForward {
            get {
                return this.sumPaymentForwardField;
            }
            set {
                this.sumPaymentForwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode {
            get {
                return this.countryEventCodeField;
            }
            set {
                this.countryEventCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode {
            get {
                return this.countryToCodeField;
            }
            set {
                this.countryToCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEventsForMailInput {
        
        private string barcodeField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRecord {
        
        private string idField;
        
        private string numberField;
        
        private string notificationTypeIDField;
        
        private string notificationTypeNameField;
        
        private string notificationStatusIDField;
        
        private string notificationStatusNameField;
        
        private System.DateTime notificationStatusDateField;
        
        private string sendedIDField;
        
        private string sourceOperationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NotificationTypeID {
            get {
                return this.notificationTypeIDField;
            }
            set {
                this.notificationTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationTypeName {
            get {
                return this.notificationTypeNameField;
            }
            set {
                this.notificationTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NotificationStatusID {
            get {
                return this.notificationStatusIDField;
            }
            set {
                this.notificationStatusIDField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationStatusName {
            get {
                return this.notificationStatusNameField;
            }
            set {
                this.notificationStatusNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NotificationStatusDate {
            get {
                return this.notificationStatusDateField;
            }
            set {
                this.notificationStatusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SendedID {
            get {
                return this.sendedIDField;
            }
            set {
                this.sendedIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceOperation {
            get {
                return this.sourceOperationField;
            }
            set {
                this.sourceOperationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public partial class CustomDutyEvent {
        
        private string numberField;
        
        private System.DateTime eventDateTimeField;
        
        private bool eventDateTimeFieldSpecified;
        
        private string eventTypeField;
        
        private string eventNameField;
        
        private string indexToField;
        
        private string indexEventField;
        
        private string countryEventCodeField;
        
        private string countryToCodeField;
        
        private string sumPaymentForwardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateTimeSpecified {
            get {
                return this.eventDateTimeFieldSpecified;
            }
            set {
                this.eventDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndexTo {
            get {
                return this.indexToField;
            }
            set {
                this.indexToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndexEvent {
            get {
                return this.indexEventField;
            }
            set {
                this.indexEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode {
            get {
                return this.countryEventCodeField;
            }
            set {
                this.countryEventCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode {
            get {
                return this.countryToCodeField;
            }
            set {
                this.countryToCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SumPaymentForward {
            get {
                return this.sumPaymentForwardField;
            }
            set {
                this.sumPaymentForwardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public partial class CustomDutyEventsForMailInput {
        
        private string barcodeField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class UserParameters {
        
        private Rtm02Parameter sendCtgField;
        
        private string sndrField;
        
        private string rcpnField;
        
        /// <remarks/>
        public Rtm02Parameter SendCtg {
            get {
                return this.sendCtgField;
            }
            set {
                this.sendCtgField = value;
            }
        }
        
        /// <remarks/>
        public string Sndr {
            get {
                return this.sndrField;
            }
            set {
                this.sndrField = value;
            }
        }
        
        /// <remarks/>
        public string Rcpn {
            get {
                return this.rcpnField;
            }
            set {
                this.rcpnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Rtm02Parameter {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationParameters {
        
        private Rtm02Parameter operTypeField;
        
        private Rtm02Parameter operAttrField;
        
        private System.DateTime operDateField;
        
        /// <remarks/>
        public Rtm02Parameter OperType {
            get {
                return this.operTypeField;
            }
            set {
                this.operTypeField = value;
            }
        }
        
        /// <remarks/>
        public Rtm02Parameter OperAttr {
            get {
                return this.operAttrField;
            }
            set {
                this.operAttrField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OperDate {
            get {
                return this.operDateField;
            }
            set {
                this.operDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class ItemParameters {
        
        private string barcodeField;
        
        private string internumField;
        
        private bool validRuTypeField;
        
        private bool validEnTypeField;
        
        private string complexItemNameField;
        
        private Rtm02Parameter mailRankField;
        
        private Rtm02Parameter postMarkField;
        
        private Rtm02Parameter mailTypeField;
        
        private Rtm02Parameter mailCtgField;
        
        private string massField;
        
        private string maxMassRUField;
        
        private string maxMassENField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Internum {
            get {
                return this.internumField;
            }
            set {
                this.internumField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidRuType {
            get {
                return this.validRuTypeField;
            }
            set {
                this.validRuTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidEnType {
            get {
                return this.validEnTypeField;
            }
            set {
                this.validEnTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ComplexItemName {
            get {
                return this.complexItemNameField;
            }
            set {
                this.complexItemNameField = value;
            }
        }
        
        /// <remarks/>
        public Rtm02Parameter MailRank {
            get {
                return this.mailRankField;
            }
            set {
                this.mailRankField = value;
            }
        }
        
        /// <remarks/>
        public Rtm02Parameter PostMark {
            get {
                return this.postMarkField;
            }
            set {
                this.postMarkField = value;
            }
        }
        
        /// <remarks/>
        public Rtm02Parameter MailType {
            get {
                return this.mailTypeField;
            }
            set {
                this.mailTypeField = value;
            }
        }
        
        /// <remarks/>
        public Rtm02Parameter MailCtg {
            get {
                return this.mailCtgField;
            }
            set {
                this.mailCtgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MaxMassRU {
            get {
                return this.maxMassRUField;
            }
            set {
                this.maxMassRUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MaxMassEN {
            get {
                return this.maxMassENField;
            }
            set {
                this.maxMassENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class FinanceParameters {
        
        private string paymentField;
        
        private string valueField;
        
        private string massRateField;
        
        private string insrRateField;
        
        private string airRateField;
        
        private string rateField;
        
        private string customDutyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MassRate {
            get {
                return this.massRateField;
            }
            set {
                this.massRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string InsrRate {
            get {
                return this.insrRateField;
            }
            set {
                this.insrRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string AirRate {
            get {
                return this.airRateField;
            }
            set {
                this.airRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CustomDuty {
            get {
                return this.customDutyField;
            }
            set {
                this.customDutyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Country {
        
        private int idField;
        
        private string code2AField;
        
        private string code3AField;
        
        private string nameField;
        
        private string nameRUField;
        
        private string nameENField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code2A {
            get {
                return this.code2AField;
            }
            set {
                this.code2AField = value;
            }
        }
        
        /// <remarks/>
        public string Code3A {
            get {
                return this.code3AField;
            }
            set {
                this.code3AField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string NameRU {
            get {
                return this.nameRUField;
            }
            set {
                this.nameRUField = value;
            }
        }
        
        /// <remarks/>
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Address {
        
        private string indexField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AddressParameters {
        
        private Address destinationAddressField;
        
        private Address operationAddressField;
        
        private Country mailDirectField;
        
        private Country countryFromField;
        
        private Country countryOperField;
        
        /// <remarks/>
        public Address DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
            }
        }
        
        /// <remarks/>
        public Address OperationAddress {
            get {
                return this.operationAddressField;
            }
            set {
                this.operationAddressField = value;
            }
        }
        
        /// <remarks/>
        public Country MailDirect {
            get {
                return this.mailDirectField;
            }
            set {
                this.mailDirectField = value;
            }
        }
        
        /// <remarks/>
        public Country CountryFrom {
            get {
                return this.countryFromField;
            }
            set {
                this.countryFromField = value;
            }
        }
        
        /// <remarks/>
        public Country CountryOper {
            get {
                return this.countryOperField;
            }
            set {
                this.countryOperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRecord {
        
        private AddressParameters addressParametersField;
        
        private FinanceParameters financeParametersField;
        
        private ItemParameters itemParametersField;
        
        private OperationParameters operationParametersField;
        
        private UserParameters userParametersField;
        
        /// <remarks/>
        public AddressParameters AddressParameters {
            get {
                return this.addressParametersField;
            }
            set {
                this.addressParametersField = value;
            }
        }
        
        /// <remarks/>
        public FinanceParameters FinanceParameters {
            get {
                return this.financeParametersField;
            }
            set {
                this.financeParametersField = value;
            }
        }
        
        /// <remarks/>
        public ItemParameters ItemParameters {
            get {
                return this.itemParametersField;
            }
            set {
                this.itemParametersField = value;
            }
        }
        
        /// <remarks/>
        public OperationParameters OperationParameters {
            get {
                return this.operationParametersField;
            }
            set {
                this.operationParametersField = value;
            }
        }
        
        /// <remarks/>
        public UserParameters UserParameters {
            get {
                return this.userParametersField;
            }
            set {
                this.userParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AuthorizationHeader {
        
        private string loginField;
        
        private string passwordField;
        
        private string mustUnderstandField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        public string mustUnderstand {
            get {
                return this.mustUnderstandField;
            }
            set {
                this.mustUnderstandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class LanguageDataLanguage {
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRequest {
        
        private string barcodeField;
        
        private string languageField;
        
        public SmsHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getOperationHistoryCompletedEventHandler(object sender, getOperationHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOperationHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOperationHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationHistoryRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationHistoryRecord[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getLanguagesCompletedEventHandler(object sender, getLanguagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLanguagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLanguagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LanguageDataLanguage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LanguageDataLanguage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getCustomDutyEventsForMailCompletedEventHandler(object sender, getCustomDutyEventsForMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomDutyEventsForMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomDutyEventsForMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomDutyEvent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomDutyEvent[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getSmsHistoryCompletedEventHandler(object sender, getSmsHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSmsHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSmsHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SmsHistoryRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SmsHistoryRecord[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PostalOrderEventsForMailCompletedEventHandler(object sender, PostalOrderEventsForMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalOrderEventsForMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalOrderEventsForMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostalOrderEvent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostalOrderEvent[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591